version: "3"

services:
  postgres_container:
    image:  postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    ports:
      - 5432:5432

  redis_container:
    image: redis
    ports:
      - "6379:6379"

  worker_container:
    build: ./worker
    depends_on:
      - redis_container
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@postgres_container:5432/chatbot
      - SENDGRID_API_KEY=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
    volumes:
      - ./worker/worker.py:/app/worker.py

  chatbot_parser:
    build: ./chatbot_parser
    ports:
      - 5050:5050
    depends_on:
      - postgres_container
      - redis_container
      - worker_container

  shrug_command:
    build: ./shrug_command
    ports:
      - 5051:5051
    
  email_server:
    build: ./email
    ports:
      - 5052:5052
    environment:
      - SENDGRID_API_KEY=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
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@postgres_container:5432/chatbot
    depends_on:
      - worker_container
      - redis_container
      - postgres_container
    volumes:
      - ./worker/worker.py:/app/worker.py

  job_viewer:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis_container
      - worker_container